name: jbb_app_v2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  basic_utils: ^5.7.0
  dartz: ^0.10.1
  dio: ^5.5.0+1
  flutter_riverpod: ^2.5.1
  flutter_staggered_grid_view: ^0.7.0
  freezed_annotation: ^2.4.4
  internet_connection_checker: ^1.0.0+1
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.2.3
  skeletonizer: ^1.4.2
  sliding_up_panel: ^2.0.0+1
  flex_color_scheme: ^7.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Light.ttf
        - asset: assets/fonts/DMSans-Medium.ttf
        - asset: assets/fonts/DMSans-Thin.ttf
          weight: 700
