name: jbb_app_v5
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  badges: ^3.1.2
  cached_video_player_plus: ^3.0.3
  camerakit_flutter: ^1.0.1
  carousel_slider: ^5.0.0
  dio: ^5.7.0
  firebase_auth: ^5.3.0
  firebase_core: ^3.5.0
  flutter:
    sdk: flutter
  flutter_exit_app: ^1.1.4
  flutter_riverpod: ^2.5.1
  flutter_slidable: ^3.1.1
  flutter_staggered_grid_view: ^0.7.0
  fluttertoast: ^8.2.8
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  model_viewer_plus: ^1.7.0
  path_provider: ^2.1.4
  photo_view: ^0.15.0
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/themes/custom/
    - assets/themes/googleButtons/
    - assets/images/


